[bot_tokens]
    Main = ""
    Testing = ""

[api_tokens]
    DagpiAPI = ""
    TopGG = ""
    GitHub = ""

[webhooks]
    join_log = ""
    error_log = ""
    command_log = ""

[postgresql]  
    host = ""
    port = 5432
    user = ""
    database = ""
    password = ""